### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by Syavel** [redDwarf03/my-idena#12]
I got a blank screen when i'm on the home tab of the app (app should be connected to my node i did the "tutorial")
![image](https://user-images.githubusercontent.com/32241006/91456680-d8919200-e883-11ea-9e71-47e7e65d8b74.png)

Device : Galaxy A5 2017
OS : Android  8.0.0
Version : v20200823.1

**Comment by sse03** [comment]
Could you send me screens for about and parameters pages please

**Comment by Syavel** [comment]
![image](https://user-images.githubusercontent.com/32241006/91479485-cd4d5f00-e8a1-11ea-97ca-d48b32739a42.png)
![image](https://user-images.githubusercontent.com/32241006/91479487-d0484f80-e8a1-11ea-861d-7e5407ee66a0.png)

**Comment by redDwarf03** [comment]
ok. could you activate the simulation mode please (are you french ?)

**Comment by Syavel** [comment]
Oui je peux :p mais ça me fait toujours pareil

**Comment by redDwarf03** [comment]
Du coup c’est peut être que ton tél ne voit pas ton pc.
Tu es sur Linux ou pc?

**Comment by Syavel** [comment]
Possible je suis sous windows là
Je peux tester sous linux si tu veux

**Comment by redDwarf03** [comment]
lot of changes since this issue. i close for the moment
