### ISSUE TITLE
Not open

### ISSUE THREAD

**Issue by cdmitriy** [redDwarf03/my-idena#14]
![Screenshot_20200907-103343](https://user-images.githubusercontent.com/34123531/92360599-bdc9e380-f0f5-11ea-9a27-83b91f275c4a.jpg)

**Comment by redDwarf03** [comment]
= issue#12
Please give android version and phone model

**Comment by cdmitriy** [comment]
Android 9, samsung g950f (s8) model phone

**Comment by redDwarf03** [comment]
Thx
