### ISSUE TITLE
Suggestion api-key and endpoint via QR code

### ISSUE THREAD

**Issue by ligi** [redDwarf03/my-idena#19]
I think it would be great if one does not have to enter the api-key and endpoint but scan it via QR code.
The QR-code could be dumped on the console (I could write the dumping app - have a nice lib for this - should be work of =<1/2h - https://github.com/walleth/console-barcodes) - or perhaps we can get the @idena-network team to dump it in the node console output and/or the app.)

**Comment by redDwarf03** [comment]
Thx for the idea. I’ll tell to Andrew

**Comment by redDwarf03** [comment]
available in v2
