### ISSUE TITLE
Suggestion: Pin password for opening app

### ISSUE THREAD

**Issue by jugi1** [redDwarf03/my-idena#5]
Do you think adding pin password for opening app would be good to improve security?

**Comment by redDwarf03** [comment]
I think the security of access to the phone (pin code, facial recognition or fingerprint) is sufficient. 
The processes provided by the application don’t require today, in my opinion, additional security.
I keep the idea however to add this option in a future stable version

**Comment by redDwarf03** [comment]
available in v2
