### ISSUE TITLE
Flips images mixed

### ISSUE THREAD

**Issue by jugi1** [redDwarf03/my-idena#6]
** Precise the version of my-idena **
It's displayed at the top right of the app. For example "Campaign 202008190.1". 

**Describe the bug**
Flips images are mixed and I can't see full flips

**To Reproduce**
1. Go to Validation simultaion

**Expected behavior**
Flips images are mixed and I can't see full flips

**Screenshots**
https://i.imgur.com/8ilPmsA.jpg
https://i.imgur.com/wIgJDYb.jpg

**Smartphone (please complete the following information):**
 - Device: Samsung
 - OS: Android

**Additional context**
Great work!

**Comment by redDwarf03** [comment]
Ok. I’ll check this.
Could you precise the model Samsung exactly to determine the screen resolution
Thx
