### ISSUE TITLE
Make the settings fields for connecting to a remote host editable

### ISSUE THREAD

**Issue by serdrdoor** [redDwarf03/my-idena#7]
Make the settings fields for connecting to a remote host editable:

- Node address
- Node api key

![image](https://user-images.githubusercontent.com/11815105/90953756-ed7eb780-e476-11ea-8da8-897a51719167.png)

by analogy with the desktop client

**Comment by serdrdoor** [comment]
for Beta version 20200829.1:

![image](https://user-images.githubusercontent.com/11815105/91657150-89d43a00-eac7-11ea-893a-7d0e9c23beef.png)

**Comment by redDwarf03** [comment]
cf issue #12
